--Tạo key SYMMETRIC KEY với tên MAHOAQLBH (Quản lý bán hàng) 
CREATE SYMMETRIC KEY MAHOAQLBH
WITH ALGORITHM = AES_256
ENCRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';
GO

--Tạo một Procedure với tên NHAPDLKH để insert dữ liệu vào table KHACHHANG
ALTER PROCEDURE NHAPDLKH
    @InputString VARCHAR(10),
    @InputString2 NVARCHAR(50),
	@InputString3 NVARCHAR(200),
	@InputString4 VARCHAR(10),
	@InputString5 date,
	@InputString6 NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    OPEN SYMMETRIC KEY MAHOA
    DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';

    INSERT INTO KHACHHANG
    (
        MaKH,
        TenKH,
		DiaChi,
		SDT,
		NgaySinh,
		STK
    )
    VALUES
    ( @InputString,ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString2)), 
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString3)),
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString4)),
		@InputString5,
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString6)));

    CLOSE SYMMETRIC KEY MAHOA;

END;
go


--Trigger cho bảng KHACHHANG
ALTER trigger tgKHACHHANG
ON KHACHHANG
FOR INSERT
AS
DECLARE @MaKH VARCHAR(100), @TenKH NVARCHAR(50), @DiaChi NVARCHAR(200), @SDT NVARCHAR(100), @NgaySinh date, @STK NVARCHAR(100)
BEGIN
	SET @MaKH= (SELECT MaKH FROM inserted)
	SET @TenKH= (SELECT TenKH FROM inserted)
	SET @DiaChi= (SELECT DiaChi FROM inserted)
	SET @SDT= (SELECT SDT FROM inserted)
	SET @NgaySinh= (SELECT NgaySinh FROM inserted)
	SET @STK= (SELECT STK FROM inserted)
	ALTER TABLE HOADON NOCHECK CONSTRAINT HD_KH
	DELETE FROM KHACHHANG WHERE MaKH=@MaKH
	EXEC NHAPDLKH @MaKH, @TenKH, @DiaChi, @SDT, @NgaySinh, @STK;
	ALTER TABLE HOADON CHECK CONSTRAINT HD_KH
END



--Tạo một Procedure với tên NHAPDLNV để insert dữ liệu vào table NHANVIEN
ALTER PROCEDURE NHAPDLNV
    @InputString VARCHAR(10),
    @InputString2 NVARCHAR(50),
	@InputString3 NVARCHAR(200),
	@InputString4 date,
	@InputString5 VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    OPEN SYMMETRIC KEY MAHOA
    DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';

    INSERT INTO NHANVIEN
    (
        MaNV,
        TenNV,
		DiaChi,
		NgaySinh,
		SDT
    )
    VALUES
       ( @InputString,ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString2)), 
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString3)),
		@InputString4,
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString5)));

    CLOSE SYMMETRIC KEY MAHOA;

END;
go

--Trigger cho bảng NHANVIEN
ALTER trigger tgNHANVIEN
ON NHANVIEN
FOR INSERT
AS
DECLARE @MaNV VARCHAR(100), @TenNV NVARCHAR(50), @DiaChi NVARCHAR(200), @NgaySinh date, @SDT NVARCHAR(100)
BEGIN
	SET @MaNV= (SELECT MaNV FROM inserted)
	SET @TenNV= (SELECT TenNV FROM inserted)
	SET @DiaChi= (SELECT DiaChi FROM inserted)
	SET @NgaySinh= (SELECT NgaySinh FROM inserted)
	SET @SDT= (SELECT SDT FROM inserted)
	ALTER TABLE PHIEUNHAP NOCHECK CONSTRAINT PN_NV
	ALTER TABLE HOADON NOCHECK CONSTRAINT HD_NV
	DELETE FROM NHANVIEN WHERE MaNV=@MaNV
	EXEC NHAPDLNV @MaNV, @TenNV, @DiaChi,  @NgaySinh, @SDT;
	ALTER TABLE PHIEUNHAP CHECK CONSTRAINT PN_NV
	ALTER TABLE HOADON CHECK CONSTRAINT HD_KH
END


--Tạo một Procedure với tên NHAPDLNCC để insert dữ liệu vào table NHACUNGCAP
ALTER PROCEDURE NHAPDLNCC
    @InputString VARCHAR(10),
    @InputString2 NVARCHAR(50),
	@InputString3 NVARCHAR(200),
	@InputString4 VARCHAR(10),
	@InputString5 NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    OPEN SYMMETRIC KEY MAHOA
    DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';

    INSERT INTO NHACUNGCAP
    (
        MaNCC,
        TenNCC,
		DiaChi,
		SDT,
		STK
    )
    VALUES
       ( @InputString,ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString2)), 
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString3)),
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString4)),
		ENCRYPTBYKEY(KEY_GUID('MAHOA'), CONVERT(VARBINARY(MAX), @InputString5)));

    CLOSE SYMMETRIC KEY MAHOA;

END;
GO

--Trigger cho bảng NHACUNGCAP
ALTER trigger tgNHACUNGCAP
ON NHACUNGCAP
FOR INSERT
AS
DECLARE @MaNCC VARCHAR(100), @TenNCC NVARCHAR(50), @DiaChi NVARCHAR(200), @SDT NVARCHAR(100), @STK NVARCHAR(100)
BEGIN
	SET @MaNCC= (SELECT MaNCC FROM inserted)
	SET @TenNCC= (SELECT TenNCC FROM inserted)
	SET @DiaChi= (SELECT DiaChi FROM inserted)
	SET @SDT= (SELECT SDT FROM inserted)
	SET @STK= (SELECT STK FROM inserted)
	ALTER TABLE PHIEUNHAP NOCHECK CONSTRAINT PN_NCC
	DELETE FROM NHACUNGCAP WHERE MaNCC=@MaNCC
	EXEC NHAPDLNCC @MaNCC, @TenNCC, @DiaChi, @SDT, @STK;
	ALTER TABLE PHIEUNHAP CHECK CONSTRAINT PN_NCC
END


--Tuy vấn dữ liệu
SELECT * FROM NHACUNGCAP
SELECT * FROM NHANVIEN
SELECT * FROM KHACHHANG



--Để xem kết quả dữ liệu đã mã hóa.

OPEN SYMMETRIC KEY MAHOA
DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';
SELECT CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(TenNCC)),
		CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(DiaChi)),
		CONVERT(VARCHAR(MAX), DECRYPTBYKEY(SDT)),
		CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(STK))
FROM NHACUNGCAP;
CLOSE SYMMETRIC KEY MAHOA;


OPEN SYMMETRIC KEY MAHOA
DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';
SELECT CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(TenNV)),
		CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(DiaChi)),
		NgaySinh,
		CONVERT(VARCHAR(MAX), DECRYPTBYKEY(SDT))
FROM NHANVIEN;
CLOSE SYMMETRIC KEY MAHOA;


OPEN SYMMETRIC KEY MAHOA
DECRYPTION BY PASSWORD = '23987hxJKL969#ghf0%94467GRkjg5k3fd117r$$#1946kcj$n44nhdlj';
SELECT CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(Tenkh)),
		CONVERT(NVARCHAR(MAX), DECRYPTBYKEY(DiaChi)),
		NgaySinh,
		CONVERT(VARCHAR(MAX), DECRYPTBYKEY(SDT))
FROM KHACHHANG;
CLOSE SYMMETRIC KEY MAHOA;


